name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple Js Actions
        id: greet
        uses: actions/hello-world-javascript-action@v1.1
        with:
         who-to-greet: Warren Brown
      - name: Log Greeted Time
        run: echo "${{ steps.greet.outputs.time}}"
