name: Code Checkout

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  lint:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous runs-on
        uses: styfle/cancel-workflow-action@0.11.0

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3.5.3

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
        with:
          node-version: 16

      - name: NPM or Yarn install with caching
        uses: bahmutov/npm-install@v1.6.0

      - name: Type check
        run: yarn run format:check
